name: Besom

on:
  push:
    branches: [ develop ]

env:
  TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  format:
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v6.3
    - uses: VirtusLab/scala-cli-setup@v0.1
    - name: Scalafmt check
      run: |
        scala-cli fmt src --check -F --respect-project-filters || (
          echo "To format code run"
          echo "  scala-cli fmt ."
          exit 1
        )

  build:
    runs-on: ${{ matrix.OS }}
    strategy:
      matrix:
        OS: ["ubuntu-latest", "macos-latest"]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v6.3
    - uses: VirtusLab/scala-cli-setup@v0.1
    - uses: arduino/setup-protoc@v1

    - name: Clean workspace
      run: |
        scala-cli clean . && rm -fr ./target

    - name: Fetch & compile protobuf 
      run: |
        scala-cli run ./scripts -M proto -- all

    - name: Run tests
      run: scala-cli test src
